### ISSUE TITLE
[Bug] Complete description not shown after creating a service

### ISSUE THREAD

**Issue by arsalananwar11** [gcivil-nyu-org/wed-fall24-team1#182]
**Steps to reproduce:**

- Go to https://nycservicefinder.live/services/create/
- Create a listing 
- Add multiple description items with the same key but different values
- Create Service 

**Current:**
System accepts all the description items without flagging any error
![image](https://github.com/user-attachments/assets/b1e791d7-2ebf-420b-a42d-cd4ca09e484f)

**System showing only one description item**
![image](https://github.com/user-attachments/assets/ea8dc94d-baf5-44f5-a88c-d51ab5a49f0b)

**Expected:**
Info shown to the user specifying that the keys have to be unique (i dont think its mentioned in the doc either, please correct me if I am wrong)

**Comment by KartikeySharma** [comment]
Its technically a duplicate field and an expected behavior

**Comment by arsalananwar11** [comment]
> Its technically a duplicate field and an expected behavior

But as a service provider, I was neither informed that duplicate keys are not allowed (on the UI) nor after clicking on 'Create Service' because it created the service without any errors. Dont you think the user has to be informed that the system randomly discarded some information that user provided. (which might be critical/important)? @KartikeySharma

**Comment by KartikeySharma** [comment]
> > Its technically a duplicate field and an expected behavior
> 
> But as a service provider, I was neither informed that duplicate keys are not allowed (on the UI) nor after clicking on 'Create Service' because it created the service without any errors. Dont you think the user has to be informed ?

If we are logically speaking here, a service provider would usually use different keys per item in a normal scenario. If they do not (as in your scenario), the system usually just picks one of the values to set, so it is the intended behavior. If you ask for this issue to be communicated to the user via the UI, this could be easily done with a simple HTML/CSS constraint. I would consider this an enhancement or suggestion rather than a bug @arsalananwar11

**Comment by arsalananwar11** [comment]
> > > Its technically a duplicate field and an expected behavior
> > 
> > 
> > But as a service provider, I was neither informed that duplicate keys are not allowed (on the UI) nor after clicking on 'Create Service' because it created the service without any errors. Dont you think the user has to be informed ?
> 
> If we are logically speaking here, a service provider would usually use different keys per item in a normal scenario. If they do not (as in your scenario), the system usually just picks one of the values to set, so it is the intended behavior. If you ask for this issue to be communicated to the user via the UI, this could be easily done with a simple HTML/CSS constraint. I would consider this an enhancement or suggestion rather than a bug @arsalananwar11

I believe that any user provided information being discarded without user's knowledge is a bug which needs to be communicated. Also, what do you think is the definition of a bug? Thanks @KartikeySharma

**Comment by omerfarukbasar** [comment]
@arsalananwar11 keeping this on topic, I understand your concern about user communication. While I see this as expected system behavior, I agree the UI could be enhanced to handle duplicate keys. We'll create a task to add a validation message as an improvement. Thanks for pointing this out! :)

**Comment by arsalananwar11** [comment]
> @arsalananwar11 keeping this on topic, I understand your concern about user communication. While I see this as expected system behavior, I agree the UI could be enhanced to handle duplicate keys. We'll create a task to add a validation message as an improvement. Thanks for pointing this out! :)

Hey @omerfarukbasar, I think you got my concern wrong. My concern is with the user's data being deleted without the knowledge of the user. This is the reason why I think it is a bug! No where in your document have you specified that duplicate keys should not be entered, neither is it indicated to the user on the UI, which is why it is a fair game! I leave it to your best hands to take it forward and to the broader team including @gennadiycivil and @anthonynikhilreddy to make a call if its a bug.

All the very best! Looking forward to see this product taking its final shape!

**Comment by omerfarukbasar** [comment]
@arsalananwar11 we are not denying what you found is a bug. We already established that we are going to address this. I see no point in prolonging this thread over semantics. Also, please refrain from bringing the TA and Professor into this over a trivial matter.

**Comment by arsalananwar11** [comment]
> @arsalananwar11 we are not denying what you found is a bug. We already established that we are going to address this. I see no point in prolonging this thread over semantics. Also, please refrain from bringing the TA and Professor into this over a trivial matter.

@omerfarukbasar 
1. I see misalignment in your team about what each member thinks about this. You think its a bug while Karthikey thinks its not (refer attached snippet) . Just to be clear, it is not bad to have issues (bugs/enhancements/whatever) in the application and I am not trying to put you in a spot. My job was to test as a part of the course and that is what I did. So nothing to get so defensive about!
2. I wanted to hear from professor about what can be classified as a bug and what issues as enhancements. We are all here to learn and hence, there's nothing wrong in taking the opinion of the professor and TA whose course I am taking. So nothing trivial, sorry!

FYI, I wouldn't be following this thread further. We can connect on slack if you need any other information on this issue! So feel free to send your message on slack (if any)!

![image](https://github.com/user-attachments/assets/fa91aecc-eb70-4ac9-825e-68d2bbd347ea)
