### ISSUE TITLE
[BUG] Incomplete address tagged to a random location

### ISSUE THREAD

**Issue by arsalananwar11** [gcivil-nyu-org/wed-fall24-team1#183]
Steps to reproduce:

- Go to Create Service
- Add a service with incomplete address
- System tags it to a random place away from where the user is located even if 'location sharing' is enabled

Current:
![image](https://github.com/user-attachments/assets/fcc8d629-1880-4e16-b324-89804a23661e)

Geotagged the restroom somewhere in Philly (believe me, I'm in NYC)!
![image](https://github.com/user-attachments/assets/c1c1793b-19e1-4efb-aded-f082d89ecd0e)

Suggestions:

- Suggestion 1: Provide users the option to view if the  geotagging is right
- Suggestion 2: Maybe not auto tag locations that are ambiguous

**Comment by omerfarukbasar** [comment]
This is known issue with the geocoding API. We specifically mentioned this on the testing document
<img width="717" alt="Screenshot 2024-11-14 at 5 09 10 PM" src="https://github.com/user-attachments/assets/054eeae9-29a3-48ce-ba81-7bcd052bab45">

**Comment by KartikeySharma** [comment]
Adding to @omerfarukbasar 

If you add 56th Street Brooklyn, then it gets updated to the correct location.

Images:
![image](https://github.com/user-attachments/assets/f50fad63-f458-4462-a64f-e74d1af3dfa7)

![image](https://github.com/user-attachments/assets/9250d292-eeb6-450e-b7dc-4583513a1238)

**Comment by arsalananwar11** [comment]
Thanks both of you for clarifying! Overall, great!
