### ISSUE TITLE
[Bug] date and time after submitting review is inaccurate

### ISSUE THREAD

**Issue by soniasusanto** [gcivil-nyu-org/wed-fall24-team1#184]
Steps to reproduce:
- Log in to https://nycservicefinder.live/home/
- Click on Brooklyn Bridge Park
- Click on 'View Details Below' in the marker
- Submit a review
- Notice the date and time are inaccurate

In the screenshot below, the date is Nov 14, time is 8:42pm but in the review, it is Nov 15 and 1:42am
<img width="1402" alt="Screenshot 2024-11-14 at 8 42 45 PM" src="https://github.com/user-attachments/assets/7ef41359-a30b-4f8e-ad72-7c271850aaef">

**Comment by ahhcash** [comment]
Ah, looks like its set to UTC. Nice catch @soniasusanto! Will look into this

**Comment by soniasusanto** [comment]
Btw seems like the date issue is quite widespread, not sure if I should create another ticket, maybe can be handled together.
<img width="1080" alt="Screenshot 2024-11-14 at 8 59 26 PM" src="https://github.com/user-attachments/assets/9568e5e7-af30-49e8-bb6e-8737bac9c364">

**Comment by ahhcash** [comment]
yeah we can handle it in this one.

**Comment by soniasusanto** [comment]
yea confirmed, I've tested a couple places and they all appear to have the same issue. Sounds good!
