### ISSUE TITLE
[Bug] Input fields when submitting review are not cleared if when I click on different venue on the same page

### ISSUE THREAD

**Issue by soniasusanto** [gcivil-nyu-org/wed-fall24-team1#185]
Steps to reproduce:
- Log in to https://nycservicefinder.live/home/
- Click on Brooklyn Bridge Park
- Click on 'View Details Below' in the marker
- Submit a review
- Go to another location on the same page, notice the previous review and rating is still present

Expected: Going to another location should clear the review inputs, review inputs should also clear on submit. This is cleared if we clicked on the next page in 'Public Services Near You'.

https://github.com/user-attachments/assets/752285a8-54e3-442b-9881-c6f2e9c7299a

**Comment by omerfarukbasar** [comment]
Yeah, this is a valid issue. Thanks for your input! We'll be on our way to craft a fix.

**Comment by ahhcash** [comment]
reopening as we don't have it on prod yet. (github vs zenhub conflicts lol)
