### ISSUE TITLE
Editing Forum Post to nothing results in error

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team1#188]
I couldn't figure out how to add the 'testing party' or 'bug' label ! apologies

Steps to Reproduce:
- Make a forum post
- Click the edit post button
- Remove all text
- Save Post

Expected Behavior:
- Either a user friendly error message that you cannot delete all text of a comment, or redirect to deletion process if you delete all text

Screenshots:
<img width="1512" alt="Screenshot 2024-11-15 at 7 26 06 AM" src="https://github.com/user-attachments/assets/c7e8bef6-c4a3-4041-bb35-baa47ae699bd">
<img width="1512" alt="Screenshot 2024-11-15 at 7 26 11 AM" src="https://github.com/user-attachments/assets/0870d0af-333f-4e0f-bdf3-3b5625e4e126">
<img width="1512" alt="Screenshot 2024-11-15 at 7 25 58 AM" src="https://github.com/user-attachments/assets/f95b8bca-bac8-4b29-a6a2-2a04a3962504">

**Comment by ahhcash** [comment]
nice catch @maxgrove42! to make our lives easier, i'll probably add some client side validation for this haha
