### ISSUE TITLE
Large name of service Provider gives 413

### ISSUE THREAD

**Issue by allen505** [gcivil-nyu-org/wed-fall24-team1#201]
### Description
No frontend size check on reviews

###  Steps to Reproduce

- Try to create a New service 
- Enter a large enough string into name text box
- Site gives 413
![Screenshot 2024-11-18 at 10 44 56 PM](https://github.com/user-attachments/assets/419b31fb-233f-4f83-a142-cb8ff216fd1b)

**Comment by ahhcash** [comment]
Closing as this is a duplicate, we've already detected this in #181 .
