### ISSUE TITLE
Admin only page can be accessed directly

### ISSUE THREAD

**Issue by allen505** [gcivil-nyu-org/wed-fall24-team1#202]
### Description
No validation on Admin Dashboard

###  Steps to Reproduce
Pase the following link in browser to access the Admin only page without loggin in
https://nycservicefinder.live/admin-only-view-new-listings/
![Screenshot 2024-11-18 at 11 02 18 PM](https://github.com/user-attachments/assets/e553339c-cbd0-49b2-bcf7-ee598f98f2d7)

### Expected Behavior
Throw error when trying to logging into Admin dashboard if not logged in

**Comment by ahhcash** [comment]
@allen505 can you share a screen recording in an incognito browser tab? I tried doing what you said and directs me to log in, which is expected.

**Comment by allen505** [comment]
https://github.com/user-attachments/assets/37c2ce7d-ce3c-4721-a132-74178df68e8c

**Comment by omerfarukbasar** [comment]
@allen505 Just tried replicating it. It doesn't do whats happening on yours. I think your browser may be unintentionally caching stuff. Tested on Arc browser too

https://github.com/user-attachments/assets/f48ea072-d47e-4733-8372-976c4966dd73

**Comment by ahhcash** [comment]
@allen505 , closing this for now. I'd suggest trying it in a different browser. Please feel free to add a comment if the issue still exists, and we'll reopen it. Thanks!
